Use std::shared_ptr instead of shared_ptr
This should fix the following error:

    In file included from testfilteredcompositenode.cc:14:0:
    ../dune/typetree/filteredcompositenode.hh:234:34: error: 'shared_ptr' was not declared in this scope
           typename enable_if<enabled,shared_ptr<Node> >::type